spring:
  application:
    name: userService

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_micro_user
    username: postgres
    password: dipak
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: ESMSHikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  jackson:
#    serialization:
#      indent-output: true

server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#jwt:
#  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
#  access-token:
#    expiration: 900000 # 15 min
#  refresh-token:
#    expiration: 2532000000 # 30 days
